substitutions:
  _REGION: "us-central1"
  _ZONE: "us-central1-a"
  _SHORT_BUILD_ID: ${BUILD_ID:0:8}

steps:
  # Generate a persistent SSH key for this build run.
  # This prevents gcloud from adding a new key to the OS Login profile on every ssh/scp command.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "generate-ssh-key"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        mkdir -p /workspace/.ssh
        # Generate the SSH key
        ssh-keygen -t rsa -f /workspace/.ssh/google_compute_engine -N '' -C gcb
        # Save the public key content to a file for the cleanup step
        cat /workspace/.ssh/google_compute_engine.pub > /workspace/gcb_ssh_key.pub
    waitFor: ["-"]

  # Create all necessary GCS buckets in parallel.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "create-buckets"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "--- Creating standard bucket ---"
        gcloud storage buckets create gs://gcsfs-test-standard-${_SHORT_BUILD_ID} --project=${PROJECT_ID} --location=${_REGION} &
        echo "--- Creating versioned bucket ---"
        gcloud storage buckets create gs://gcsfs-test-versioned-${_SHORT_BUILD_ID} --project=${PROJECT_ID} --location=${_REGION} &
        echo "--- Creating HNS bucket ---"
        gcloud storage buckets create gs://gcsfs-test-hns-${_SHORT_BUILD_ID} --project=${PROJECT_ID} --location=${_REGION} --enable-hierarchical-namespace --uniform-bucket-level-access &
        echo "--- Creating Zonal bucket ---"
        gcloud storage buckets create gs://gcsfs-test-zonal-${_SHORT_BUILD_ID} --project=${PROJECT_ID} --location=${_REGION} --placement=${_ZONE} --default-storage-class=RAPID --enable-hierarchical-namespace --uniform-bucket-level-access &

        wait

        echo "--- Enabling versioning on versioned bucket ---"
        gcloud storage buckets update gs://gcsfs-test-versioned-${_SHORT_BUILD_ID} --versioning
    waitFor: ["-"]

  # Create a GCE VM to run the tests.
  # The VM is created in the same zone as the zonal bucket to test rapid storage features.
  # It's given the 'cloud-platform' scope to allow it to access GCS and other services.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "create-vm"
    entrypoint: "gcloud"
    args:
      - "compute"
      - "instances"
      - "create"
      - "gcsfs-test-vm-${_SHORT_BUILD_ID}"
      - "--project=${PROJECT_ID}"
      - "--zone=${_ZONE}"
      - "--machine-type=n2-standard-4"
      - "--image-family=debian-13"
      - "--image-project=debian-cloud"
      - "--service-account=${_ZONAL_VM_SERVICE_ACCOUNT}"
      - "--scopes=https://www.googleapis.com/auth/cloud-platform" # Full access to project APIs
      - "--metadata=enable-oslogin=TRUE"
    waitFor: ["-"]

  # Set up the VM for integration tests.
  # This step uses 'gcloud compute ssh' to execute a script.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "setup-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        # Wait for the VM to be fully initialized and SSH to be ready.
        for i in {1..10}; do
          if gcloud compute ssh gcsfs-test-vm-${_SHORT_BUILD_ID} --zone=${_ZONE} --internal-ip --ssh-key-file=/workspace/.ssh/google_compute_engine --command="echo VM is ready"; then
            break # Break if SSH is successful
          fi
          echo "Waiting for VM to become available... (attempt $$i/10)"
          sleep 15
        done

        # Copy the source code from the Cloud Build workspace to the VM's home directory, using the generated key.
        gcloud compute scp --recurse . gcsfs-test-vm-${_SHORT_BUILD_ID}:~ --zone=${_ZONE} --internal-ip --ssh-key-file=/workspace/.ssh/google_compute_engine

        # Script to be executed on the VM.
        # This script installs dependencies, sets environment variables, and runs pytest.
        SETUP_SCRIPT="
          set -e
          echo '--- Installing dependencies on VM ---'
          sudo apt-get update > /dev/null
          sudo apt-get install -y python3-pip python3-venv fuse fuse3 libfuse2 git> /dev/null

          echo '--- Installing Python and dependencies on VM ---'
          python3 -m venv env
          source env/bin/activate

          pip install --upgrade pip > /dev/null
          # Install testing libraries explicitly, as they are not in setup.py
          pip install pytest pytest-timeout pytest-subtests pytest-asyncio fusepy google-cloud-storage > /dev/null
          pip install --upgrade --force-reinstall git+https://github.com/googleapis/python-storage.git@main
          pip install -e . > /dev/null
        "

        # Execute the script on the VM via SSH.
        gcloud compute ssh gcsfs-test-vm-${_SHORT_BUILD_ID} --zone=${_ZONE} --internal-ip --ssh-key-file=/workspace/.ssh/google_compute_engine --command="$$SETUP_SCRIPT"
    waitFor:
      - "create-vm"
      - "generate-ssh-key"

  # Run standard tests (in parallel with other tests).
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "run-standard-tests"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        TEST_SCRIPT="
          source env/bin/activate && \
          echo '--- Preparing test environment for standard tests ---' && \
          export GCSFS_TEST_BUCKET='gcsfs-test-standard-${_SHORT_BUILD_ID}' && \
          export GCSFS_TEST_VERSIONED_BUCKET='gcsfs-test-versioned-${_SHORT_BUILD_ID}' && \
          export STORAGE_EMULATOR_HOST=https://storage.googleapis.com && \
          export GCSFS_TEST_PROJECT=${PROJECT_ID} && \
          export GCSFS_TEST_KMS_KEY=projects/${PROJECT_ID}/locations/${_REGION}/keyRings/${_GCSFS_KEY_RING_NAME}/cryptoKeys/${_GCSFS_KEY_NAME} && \
          echo '--- Running standard tests on VM ---' && \
          pytest -vv -s --log-format='%(asctime)s %(levelname)s %(message)s' --log-date-format='%H:%M:%S' --color=no gcsfs/ --deselect gcsfs/tests/test_core.py::test_sign
        "
        gcloud compute ssh gcsfs-test-vm-${_SHORT_BUILD_ID} --zone=${_ZONE} --internal-ip --ssh-key-file=/workspace/.ssh/google_compute_engine --command="$$TEST_SCRIPT"
    waitFor:
      - "setup-vm"
      - "create-buckets"

  # Run extended tests on Zonal bucket (in parallel with other tests).
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "run-zonal-tests"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        TEST_SCRIPT="
          source env/bin/activate && \
          echo '--- Preparing test environment for zonal tests ---' && \
          export GCSFS_TEST_BUCKET='gcsfs-test-standard-${_SHORT_BUILD_ID}' && \
          export GCSFS_ZONAL_TEST_BUCKET='gcsfs-test-zonal-${_SHORT_BUILD_ID}' && \
          export STORAGE_EMULATOR_HOST=https://storage.googleapis.com && \
          export GCSFS_TEST_PROJECT=${PROJECT_ID} && \
          export GCSFS_TEST_KMS_KEY=projects/${PROJECT_ID}/locations/${_REGION}/keyRings/${_GCSFS_KEY_RING_NAME}/cryptoKeys/${_GCSFS_KEY_NAME} && \
          echo '--- Running Zonal tests on VM ---' && \
          ulimit -n 4096 && export GCSFS_EXPERIMENTAL_ZB_HNS_SUPPORT='true' && \
          pip install --upgrade --force-reinstall git+https://github.com/googleapis/python-storage.git@main && \
          pytest -vv -s --log-format='%(asctime)s %(levelname)s %(message)s' --log-date-format='%H:%M:%S' --color=no gcsfs/tests/test_extended_gcsfs.py gcsfs/tests/test_zonal_file.py gcsfs/tests/test_async_gcsfs.py
        "
        gcloud compute ssh gcsfs-test-vm-${_SHORT_BUILD_ID} --zone=${_ZONE} --internal-ip --ssh-key-file=/workspace/.ssh/google_compute_engine --command="$$TEST_SCRIPT"
    waitFor:
      - "setup-vm"
      - "create-buckets"

  # Run tests on HNS bucket (in parallel with other tests).
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "run-hns-tests"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        TEST_SCRIPT="
          source env/bin/activate && \
          echo '--- Preparing test environment for HNS tests ---' && \
          export GCSFS_TEST_BUCKET='gcsfs-test-hns-${_SHORT_BUILD_ID}' && \
          export GCSFS_ZONAL_TEST_BUCKET='gcsfs-test-hns-${_SHORT_BUILD_ID}' && \
          export GCSFS_HNS_TEST_BUCKET='gcsfs-test-hns-${_SHORT_BUILD_ID}' && \
          export STORAGE_EMULATOR_HOST=https://storage.googleapis.com && \
          export GCSFS_TEST_PROJECT=${PROJECT_ID} && \
          export GCSFS_TEST_KMS_KEY=projects/${PROJECT_ID}/locations/${_REGION}/keyRings/${_GCSFS_KEY_RING_NAME}/cryptoKeys/${_GCSFS_KEY_NAME} && \
          echo '--- Running HNS tests on VM ---' && \
          export GCSFS_EXPERIMENTAL_ZB_HNS_SUPPORT='true' && \
          pytest -vv -s --log-format='%(asctime)s %(levelname)s %(message)s' --log-date-format='%H:%M:%S' --color=no gcsfs/ --deselect gcsfs/tests/test_extended_gcsfs.py --deselect gcsfs/tests/test_zonal_file.py --deselect gcsfs/tests/test_core_versioned.py --deselect gcsfs/tests/test_core.py::test_sign --deselect gcsfs/tests/test_core.py::test_info_on_directory_with_only_subdirectories"
        gcloud compute ssh gcsfs-test-vm-${_SHORT_BUILD_ID} --zone=${_ZONE} --internal-ip --ssh-key-file=/workspace/.ssh/google_compute_engine --command="$$TEST_SCRIPT"
    waitFor:
      - "setup-vm"
      - "create-buckets"

  # --- Cleanup Steps ---

  # Clean up the SSH key from the OS Login profile.
  # This step is crucial to prevent key accumulation.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "cleanup-ssh-key"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "--- Removing SSH key from OS Login profile to prevent accumulation ---"
        gcloud compute os-login ssh-keys remove \
          --key-file=/workspace/gcb_ssh_key.pub || true
    waitFor:
      - "run-standard-tests"
      - "run-zonal-tests"
      - "run-hns-tests"

  # Delete the GCE VM.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "delete-vm"
    entrypoint: "gcloud"
    args:
      - "compute"
      - "instances"
      - "delete"
      - "gcsfs-test-vm-${_SHORT_BUILD_ID}"
      - "--zone=${_ZONE}"
      - "--quiet"
    waitFor:
      - "cleanup-ssh-key"

  # Delete all GCS buckets in parallel.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "delete-buckets"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "--- Deleting test buckets in parallel ---"
        gcloud storage rm --recursive gs://gcsfs-test-standard-${_SHORT_BUILD_ID} &
        gcloud storage rm --recursive gs://gcsfs-test-versioned-${_SHORT_BUILD_ID} &
        gcloud storage rm --recursive gs://gcsfs-test-hns-${_SHORT_BUILD_ID} &
        gcloud storage rm --recursive gs://gcsfs-test-zonal-${_SHORT_BUILD_ID} &
        wait
    waitFor:
      - "run-standard-tests"
      - "run-zonal-tests"
      - "run-hns-tests"

timeout: "3600s" # 60 minutes

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: "projects/${PROJECT_ID}/locations/us-central1/workerPools/cloud-build-worker-pool"
