codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%  # Allow 0% drop.
    patch:
      default:
        target: 80%
        threshold: 0%
