ignore:
  - "gcsfs/tests/**/*"

codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%  # Allow up to 0.5% drop.
    patch:
      default:
        target: 80%
        threshold: 0%
