steps:
  # Step 3: Create a GCE VM to run the tests.
  # The VM is created in the same zone as the buckets to test zonal bucket features.
  # It's given the 'cloud-platform' scope to allow it to access GCS and other services.
  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   id: "create-vm"
  #   entrypoint: "gcloud"
  #   args:
  #     - "compute"
  #     - "instances"
  #     - "create"
  #     - "gcsfs-test-vm-5"
  #     - "--project=gcs-tess"
  #     - "--zone=us-central1-b"
  #     - "--machine-type=e2-medium"
  #     - "--image-family=debian-11"
  #     - "--image-project=debian-cloud"
  #     - "--service-account=222564316065@cloudbuild.gserviceaccount.com "
  #     - "--tags=allow-ssh"
  #     - "--scopes=https://www.googleapis.com/auth/cloud-platform" # Full access to project APIs
  #     - "--metadata=enable-oslogin=TRUE"
  #   waitFor: ["-"]
steps:
  # Step 1: Clone the private tessellations repository using the SSH key
  - name: 'gcr.io/cloud-builders/python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e


        apt-get update && apt-get install -y git ssh

        # Create the .ssh directory and set up the private key
        mkdir -p /root/.ssh

        # Set up SSH
        echo "$$SSH_KEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan github.com > /root/.ssh/known_hosts

        # Clone the repository using the SSH URL
        git clone git@github.com:google-partners/tessellations.git
        cd tessellations/benchmarks/proof-of-concept/microbenchmark/gcsfs

        echo '--- Installing Python and dependencies on VM ---'
        # This will now work in the 'python' builder image.
        python3 -m venv env
        source env/bin/activate

        pip install --upgrade pip

        echo '--- Preparing test environment on VM ---'
        python main.py 8192_gcs_central1 --benchmark init-delete-dataset
        python main.py 8192_gcs_central1 --benchmark delete
    secretEnv: ['SSH_KEY']

substitutions:
  _HEAD_BRANCH: ${HEAD_BRANCH}

availableSecrets:
  secretManager:
  - versionName: projects/gcs-tess/secrets/github-deploy-key-tessellations-amaloo/versions/latest
    env: 'SSH_KEY'