substitutions:
  _REGION: "us-central1"
  _ZONE: "us-central1-a"
  _SHORT_BUILD_ID: ${BUILD_ID:0:8}
  _HEAD_BRANCH: ${HEAD_BRANCH}


steps:
  - name: 'bash'
    id: 'check-label'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # _PR_LABELS="${{ github.event.pull_request.body }}"
        echo "tHIS IS LAbels: ${_PR_LABELS}"
        # Check if the label 'gcb-required' is in the _PR_LABELS variable's JSON output
        if echo "$_PR_LABELS" | grep -q "gcb-required"; then
          echo "Label 'gcb-required' found. Proceeding with full CI/CD run."
        else
          echo "Label 'gcb-required' not found. Skipping critical steps and exiting successfully."
          # If the label is NOT present, we exit with status 0 (Success).
          # This makes the Cloud Build status on GitHub green, allowing the merge.
          echo "Skipped" > /workspace/SKIP_CI
        fi
    waitFor: ["-"]
  # Step 1: Create a GCE VM to run the tests.
  # It's given the 'cloud-platform' scope to allow it to access GCS and other services.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "create-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ -f /workspace/SKIP_CI ]; then
          echo "SKIP_CI file found. Skipping VM creation step."
          exit 0
        fi
        
        # --- Original Logic Starts Here ---
        gcloud compute instances create gcsfs-test-vm-${_SHORT_BUILD_ID} \
          --project=${PROJECT_ID} \
          --zone=${_ZONE} \
          --machine-type=e2-medium \
          --image-family=debian-11 \
          --image-project=debian-cloud \
          --service-account=${_VM_SERVICE_ACCOUNT} \
          --tags=allow-ssh \
          --scopes=https://www.googleapis.com/auth/cloud-platform \
          --network-tier=PREMIUM \
          --metadata=enable-oslogin=TRUE
    waitFor: ["check-label"]


  # Step 2: Run the performance tests inside the newly created VM.
  # This step uses 'gcloud compute ssh' to execute a remote script.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "run-tests-on-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ -f /workspace/SKIP_CI ]; then
          echo "SKIP_CI file found. Skipping test run step."
          exit 0
        fi
        set -e
        # Wait for the VM to be fully initialized and SSH to be ready.
        for i in {1..10}; do
          if gcloud compute ssh gcsfs-test-vm-${_SHORT_BUILD_ID} --zone=${_ZONE} --internal-ip --quiet --command="whoami"; then
            break
          fi
          echo "Waiting for VM to become available... (attempt $$i/10)"
          sleep 15
        done
        ENCODED_KEY=$(echo "$$SSH_KEY" | base64 -w 0)
        # Script to be executed on the VM.
        # This script installs dependencies, sets environment variables, and runs pytest.
        VM_SCRIPT="
          set -e
          echo '---   SSH on VM complete---'
          mkdir -p ~/.ssh

          # Set up SSH
          echo "$$ENCODED_KEY" | base64 -d > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan github.com > ~/.ssh/known_hosts

          # Install git and python
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-venv

          # Clone the repository using the SSH URL
          git clone git@github.com:google-partners/tessellations.git
          cd tessellations/benchmarks/proof-of-concept/microbenchmark/gcsfs
          pip install -r requirements.txt
          python3 main.py 8192_objs_gcs_central1 --benchmark init-source-dataset

          # Run benchmarks in parallel
          python3 main.py 8192_objs_gcs_central1 --benchmark delete #&
          # PID1=$$!
          # python3 main.py 8192_objs_gcs_central1 --benchmark rename &
          # PID2=$$!

          # Wait for benchmarks to finish and check exit codes
          # if wait $$PID1 && wait $$PID2; then
          #   echo "Benchmarks completed successfully"
          # else
          #   echo "One or more benchmarks failed"
          #   exit 1
          # fi
        "

        # Execute the script on the VM via SSH.
        gcloud compute ssh gcsfs-test-vm-${_SHORT_BUILD_ID} --zone=${_ZONE} --internal-ip --command="$$VM_SCRIPT"
    secretEnv: ['SSH_KEY']
    waitFor:
      - "create-vm"


  # --- Cleanup Steps ---

  # Step 3: Delete the GCE VM.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "delete-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ -f /workspace/SKIP_CI ]; then
          echo "SKIP_CI file found. Skipping VM deletion step."
          exit 0
        fi
        
        gcloud compute instances delete gcsfs-test-vm-${_SHORT_BUILD_ID} \
          --zone=${_ZONE} \
          --quiet
    waitFor:
      - "run-tests-on-vm"

timeout: "3600s" # 30 minutes


options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: "projects/${PROJECT_ID}/locations/us-central1/workerPools/cloud-build-worker-pool"

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/github-deploy-key-tessellations-amaloo/versions/latest
    env: 'SSH_KEY'
