steps:
  # Step 1: Clone the private tessellations repository using the SSH key
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create the .ssh directory before using it
        mkdir -p /root/.ssh

        # Set up SSH
        echo "$$SSH_KEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan github.com > /root/.ssh/known_hosts

        # Clone the repository using the SSH URL
        git clone git@github.com:google-partners/tessellations.git
        cd tessellations/benchmarks/proof-of-concept/microbenchmark/gcsfs

        echo '--- Installing Python and dependencies on VM ---'
        python3 -m venv env
        source env/bin/activate



        echo '--- Preparing test environment on VM ---'
        python main.py 8192_gcs_central1 --benchmark init-delete-dataset
        python main.py 8192_gcs_central1 --benchmark delete
    secretEnv: ['SSH_KEY']

substitutions:
  _HEAD_BRANCH: ${HEAD_BRANCH}

availableSecrets:
  secretManager:
  - versionName: projects/gcs-tess/secrets/github-deploy-key-tessellations-amaloo/versions/latest
    env: 'SSH_KEY'