steps:
  # Step 1: Clone the private tessellations repository and run tests.
  # Using the reliable 'gcloud' builder, which includes Python 3 and system tools.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e # Exit immediately if a command exits with a non-zero status

        echo '--- Installing Git and SSH tools ---'
        # Install or update Git and SSH utilities if not present in the gcloud builder's base OS
        apt-get update && apt-get install -y git ssh

        # Create the .ssh directory and set up the private key
        mkdir -p /root/.ssh

        # Set up SSH
        echo '--- Setting up SSH Key ---'
        echo "$$SSH_KEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan github.com > /root/.ssh/known_hosts

        # Clone the repository using the SSH URL
        echo '--- Cloning Repository ---'
        git clone git@github.com:google-partners/tessellations.git

        # Navigate to the correct directory
        cd tessellations/benchmarks/proof-of-concept/microbenchmark/gcsfs

        echo '--- Setting up Python Virtual Environment ---'
        # The gcloud builder includes Python 3, so venv should work.
        python3 -m venv env
        source env/bin/activate

        echo '--- Installing dependencies ---'
        pip install --upgrade pip
        # Add your project-specific dependencies here if not installing from setup.py:
        # pip install pytest pytest-timeout pytest-asyncio

        echo '--- Running Tests ---'
        python main.py 8192_gcs_central1 --benchmark init-delete-dataset
        python main.py 8192_gcs_central1 --benchmark delete
    secretEnv: ['SSH_KEY']

substitutions:
  _HEAD_BRANCH: ${HEAD_BRANCH}

availableSecrets:
  secretManager:
  - versionName: projects/gcs-tess/secrets/github-deploy-key-tessellations-amaloo/versions/latest
    env: 'SSH_KEY'