substitutions:
  _REGION: "us-central1"
  _ZONE: "us-central1-b"
  _SHORT_BUILD_ID: ${BUILD_ID:0:8}

steps:

  # Step 3: Create a GCE VM to run the tests.
  # The VM is created in the same zone as the buckets to test zonal bucket features.
  # It's given the 'cloud-platform' scope to allow it to access GCS and other services.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "create-vm"
    args:
      - "compute"
      - "instances"
      - "create"
      - "gcsfs-test-vm-7"
      - "--project=gcs-tess"
      - "--zone=us-central1-b"
      - "--machine-type=e2-medium"
      - "--image-family=debian-11"
      - "--image-project=debian-cloud"
      - "--no-address"
      - "--service-account=222564316065-compute@developer.gserviceaccount.com"
      - "--scopes=https://www.googleapis.com/auth/cloud-platform" # Full access to project APIs
    waitFor: ["-"]

  # Step 4: Run the integration tests inside the newly created VM.
  # This step uses 'gcloud compute ssh' to execute a remote script.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "run-tests-on-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        # Wait for the VM to be fully initialized and SSH to be ready.
        for i in {1..10}; do
          if gcloud compute ssh gcsfs-test-vm-7 --zone=${_ZONE} --command="echo VM is ready"; then
            break
          fi
          echo "Waiting for VM to become available... (attempt $$i/10)"
          sleep 15
        done

        # Define the script to be executed on the VM.
        # This script installs dependencies, sets environment variables, and runs pytest.
        VM_SCRIPT="
          set -e
          echo '--- Installing git and cloning repository on VM ---'
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-venv

          # Create the .ssh directory before using it
          mkdir -p /root/.ssh

          # Set up SSH
          echo "$$SSH_KEY" > /root/.ssh/id_rsa
          chmod 400 /root/.ssh/id_rsa
          ssh-keyscan github.com > /root/.ssh/known_hosts

          # Clone the repository using the SSH URL
          git clone git@github.com:google-partners/tessellations.git

          echo '--- Installing Python and dependencies on VM ---'
          python3 -m venv env
          source env/bin/activate

          pip install --upgrade pip
          # Install testing libraries explicitly, as they are not in setup.py
          pip install pytest pytest-timeout pytest-asyncio
          pip install -e .

          echo '--- Preparing test environment on VM ---'
          cd tessellations/benchmarks/proof-of-concept/microbenchmark/gcsfs
          python main.py 8192_gcs_central1 --benchmark init-delete-dataset
          python main.py 8192_gcs_central1 --benchmark delete

        "

        # Execute the script on the VM via SSH.
        gcloud compute ssh gcsfs-test-vm-7 --zone=${_ZONE} --command="$$VM_SCRIPT"
    secretEnv: ['SSH_KEY']
    waitFor:
      - "create-vm"

  # --- Cleanup Steps ---
  # These steps will run after the test step, regardless of its success or failure,
  # to ensure resources are not left orphaned.

  # Step 5: Delete the GCE VM.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "delete-vm"
    args:
      - "compute"
      - "instances"
      - "delete"
      - "gcsfs-test-vm-7"
      - "--zone=${_ZONE}"
      - "--quiet"
    waitFor:
      - "run-tests-on-vm"

timeout: "1800s" # 30 minutes

options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _HEAD_BRANCH: ${HEAD_BRANCH}

availableSecrets:
  secretManager:
  - versionName: projects/222564316065/secrets/github-deploy-key-tessellations-amaloo/versions/1