[package]
name = "gcsfs_rust_backend"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "gcsfs_rust_backend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
google-cloud-storage = "1"
