# This workflow warns and then closes issues that have had no activity for a specified amount of time.
name: Mark and close stale issues

on:
  schedule:
    # Scheduled to run at 1:30 UTC everyday
    - cron: '30 1 * * *'
  workflow_dispatch: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      issues: write

    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 100
          days-before-issue-stale: 14
          days-before-issue-close: 7
          stale-issue-label: "status:stale"
          close-issue-reason: not_planned
          any-of-labels: "status:awaiting user response"
          remove-stale-when-updated: true
          labels-to-remove-when-unstale: "status:awaiting user response,status:stale"
          stale-issue-message: >
            This issue has been marked as stale because it has been awaiting a response for 14 days with no activity.
            It will be closed in 7 days if no further activity occurs.
          close-issue-message: >
            This issue was closed because it has been inactive for 3 weeks after awaiting user response.
            Please feel free to reopen or open a new issue if you still need assistance. Thanks!
          # Label that can be assigned to issues to exclude them from being marked as stale
          exempt-issue-labels: "override-stale"
          # Exclude Pull Requests
          days-before-pr-stale: -1
          days-before-pr-close: -1
